### ISSUE TITLE
Fields need to be dropped from data

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#100]
On the 04/15 meeting it was discussed that meeting id and topic need to be dropped from the Zoom (and probably Bluejeans) reports. Also anything containing the meeting id (like the URL) need to be dropped as well.

We need a way of doing this easily per data source. 

This includes from Zoom
```
total_meetings -> id, topic
total_webinars -> id, topic
zoom_courses_meetings -> meeting_number, topic, join_url
```

The Bluejeans script should drop meetingTitle and meetingId.

**Comment by jonespm** [comment]
The zoom_courses_meetings will still need to be dropped, this might be just incorporated into #137 directly.

**Comment by zqian** [comment]
Verified in the lti_zoom_meeting table, both meeting_id and host_id fields are with hashed values.
