### ISSUE TITLE
Use key value instead of row number for pulling canvasdatadate from UDW

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#103]
It seems like the test job failed this morning because the key-value pairs in the `unizin_metadata` table in UDW came back switched, leading to the code trying to parse `schemaversion` as a DateTime. We should just avoid this possible issue by using `pandas` to find the right row, rather than hardcoding a row number.

```
ValueError: time data '4.2.6' does not match format '%Y-%m-%d %H:%M:%S.%f%z' (match)
```

**Comment by zqian** [comment]
Verified that the data_updated_at time "UNIZIN_DATA_WAREHOUSE" source has been properly populated for recent runs. 

We may want to surface the data_updated_at values for all data sources in the Tableau view.
