### ISSUE TITLE
Remove self.conn, set_up, and tear_down methods from DBCreator

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#109]
Aside from being confusingly named (since they're only being used now for setting up a connection), the utility functions `set_up` and `tear_down` and the associated instance variable `self.conn` seem unnecessary for managing a transitory connection object. Users of `DBCreator` can just use the SQLAlchemy API from the `self.engine` object if needed, making sure to close any connections they open. See the following example.

```
db_creator_obj = DBCreator(INVENTORY_DB, APPEND_TABLE_NAMES)
conn = db_creator_obj.engine.connect()
conn.close()
```

**Comment by zqian** [comment]
verified the set_up, tear_down and self.conn are no longer in code base.
