### ISSUE TITLE
MiVideo `data_updated_at` timestamp is wrong

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#111]
I'm consistently seeing dates of `1970-01-01 00:00:02` in the `data_source_status` records associated with Big Query generated by the `mivideo` job.

https://github.com/tl-its-umich-edu/course-inventory/blob/fe54c54608344b77425f6dbcf4c1d36bf84eda05/mivideo/mivideo_extract.py#L126-L129

Based on my brief testing, if we change line 128 above to `'data_updated_at': pd.to_datetime(time.time(), unit='s', utc=True)`, this should be fixed.

**Comment by lsloan** [comment]
Apologies for the multiple commits.  I'd committed with the wrong key, an unverified one, when my usual key had expired.  I renewed my verified key and committed again.

**Comment by zqian** [comment]
verified there is no more epoch time logged into the data_source_status for recent job runs.
