### ISSUE TITLE
Accomodate multiple terms in database

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#113]
As the Winter term ends, we need to figure out how to handle multiple terms in the database. This will likely involve adding a `term` table to the database schema, as well as fetching some basic information about terms from Canvas. Here are some other questions raised during previous discussion.

* Spring/Summer actually is three different terms, so the `course_inventory` job will need to be modified to fetch data for multiple terms.
* We would probably need a way to only drop records associated with a specific term, which would require a more sophisticated `drop_records` method. (This idea needs some more discussion and thinking, so I'm moving it to a separate issue.)

**Comment by pushyamig** [comment]
I was able to test this from master branch (05/05/20 ) and I was able to run all 3 processes ["COURSE_INVENTORY", "MIVIDEO", "CANVAS_ZOOM_MEETINGS"]. Look good!
