### ISSUE TITLE
Change data type of course.sis_id to VARCHAR

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#117]
In looking at data for upcoming terms, I discovered that the SIS ID for courses can sometimes contain a letter at the end. Thus, we'll need to change the datatype for this field to `VARCHAR(something)` from `BIGINT`.

**Comment by ssciolla** [comment]
I verified in the test database that this is VARCHAR(15). We haven't seen any issues since we deployed this to the test job workflow. Marking as Done.

**Comment by zqian** [comment]
Verified the varchar change. 

However, the only non numeric value I can find for the sis_id column is "None":

SELECT DISTINCT(sis_id) FROM course WHERE sis_id NOT REGEXP '[0-9]' 
None

**Comment by zqian** [comment]
Sam reminded me an instance of non-numeric sis_id course: 

SELECT DISTINCT(sis_id) FROM course WHERE sis_id like '%A%'

Wonder what's wrong with my prior query using REGEXP, though.
