### ISSUE TITLE
Validate inputs from configuration file

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#119]
This issue was raised during discussion with @lsloan and @jonespm on PR #115.

Throughout the codebase, we mostly assume that the configuration JSON contains specific values and data types. It makes sense to validate these in some way.

A neat way to handle this -- without adding a bunch of conditions in several files -- might be to use JSON Schema to validate the configuration file's contents within `environ.py` before it gets to the rest of the codebase. @jonespm suggested looking at [this project](https://github.com/Julian/jsonschema). If anyone else has any more ideas, please share them here.

This might be related to issue #29.

**Comment by ssciolla** [comment]
I started working on this since the JSON Schema idea intrigued me. I decided to try HJSON first. Any thoughts on what I've got started at the branch linked to below? The schema itself needs a bit more work, but much of it seems to be in place. 

https://github.com/tl-its-umich-edu/course-inventory/compare/master...ssciolla:issues-29-119-hjson-plus-schema

**Comment by ssciolla** [comment]
I've done some additional work on this. I'd like to address issue #128 with this work, too, but I will wait to submit a PR at least until #124 is merged, maybe longer.

**Comment by lsloan** [comment]
:shipit: 

Also, I like this idea so much, I enabled JSON format checking in PR #116.
