### ISSUE TITLE
Clean up local flake8 (and any other lint config) files

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#125]
I noticed a few subdirectories had some local configs, I'd like to clean these up and just use the top level one if possible. It looks like the only thing that's failing for mivideo is the line length which we are overriding at the top level.

**Comment by ssciolla** [comment]
This was a good change; it's better to have only one file here. We just need to accommodate @lsloan's preference for camelCase in the `mivideo` code going forward. Marking as Done.

**Comment by jonespm** [comment]
PEP-8 dosen't accommodate for camelCase. If we have any for function names they should probably be renamed.

https://docs.quantifiedcode.com/python-anti-patterns/readability/using_camelcase_in_function_names.html

**Comment by ssciolla** [comment]
I personally don't think this is worth fighting over, but PEP does seem more rigid about it then I remember. `flake` isn't going to catch these unless we add a package, according to this StackOverflow post: https://stackoverflow.com/questions/28725116/flake8-doesnt-report-mixed-case-function-names
