### ISSUE TITLE
Write Canvas Meetings LTI to Database

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#137]
We need to change the to_csv in the canvas_zoom_meetings to write the to the database

This will involve

- [x] Creating the database schema that this will use
- [x] Writing the dataframes to the database

It may also be nice if it can update rather than delete and insert. This will require some additional research. This somewhat depends on #49 and would be improved by #114

**Comment by zqian** [comment]
verified new table lti_placement and lti_zoom_meeting are in database with right data.
