### ISSUE TITLE
Fetch account data, store in new account table

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#138]
From the Trello card created by @jennlove-um:

"The unit hierarchy in reports should be based on the UM department hierarchy used in other reporting. To do this, we need to map Canvas account_id for courses to a department ID.

The Canvas account_dim has the sis_source_id which maps to the UM deptid.  

We need to add this account data to our Canvas data for the dashboard.  We should pull the canvas_id, name, and sis_source_id from the account_dim."

The account_dim refers to UDW, but I think it would be simple and better long term to get this directly from the Canvas API. The returned `account` object and available endpoints are described [here](https://canvas.instructure.com/doc/api/accounts.html). It looks like there are probably only 100-200 different account IDs in this dataset, so either the "List accounts" or "Get single account" endpoint should work.

**Comment by zqian** [comment]
There are 147 account entries in the db now. This is not a complete set of all Canvas subaccount. I guess the reason for that is only the account with course/sections are retrieved?

**Comment by ssciolla** [comment]
@zqian, yeah, I designed it to only care about accounts related to a course. I could change it to pull all accounts, if you want. Let me know!

**Comment by jennlove-um** [comment]
@zqian My inclination is to keep pulling only the accounts that have courses in them.  There are hundreds of accounts that are unlikely to ever have courses associated with an academic term, and that feels like adding noise to the data for little to no purpose.  For example, there are over 700 accounts in the Non-Academic Program Courses account alone.  Unless we get a specific request and business need to include all accounts, I think it makes sense to include only accounts that have courses in one of the academic terms included in the data and the visualizations.

**Comment by zqian** [comment]
@ssciolla @jennlove-um I got the idea of reporting only the data needed. Is it possible that going into future term, there will be a new course associated with a new account, not reported previously in the Account table? Will the report detect the new account and add it to the account table?

**Comment by ssciolla** [comment]
Yes, with the current set up, all accounts associated with courses will be available. This is transparent in the code; unique account IDs found in the course data are fed into the account data fetching function, which specifically requests data for each account ID.

https://github.com/tl-its-umich-edu/course-inventory/blob/27383d09ba47f7fa6f0ad608bbe3b46141bae077/course_inventory/inventory.py#L278-L279

How exactly this works may be modified if or when we move towards updating (rather than dropping records), but we can ensure new accounts are handled appropriately.

**Comment by zqian** [comment]
Sounds good. I will move this the Done column in the project.
