### ISSUE TITLE
improve MiVideo category handling

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/course-inventory#150]
As discussed with @ssciolla, it would be safer to better define how categories are used to query the Kaltura API and how to transform the appropriate categories into Canvas course ID references.

The code currently uses regular expressions to find categories that begin with a prefix (`Canvas_UMich`, by default) and search them for any number and treat that as the Canvas course ID number.  It would be better to search for the specific category formats:

* `Canvas_UMich>site>channels>𝒏𝒏𝒏𝒏`
* `Canvas_UMich>site>channels>𝒏𝒏𝒏𝒏>InContext`

Questions for the implementation:

1. Avoid regular expressions.  They're great tools, but they can sometimes match strings that weren't intended (e.g., #188).  If regular expressions must be used, reduce the amount of (or eliminate) globbing operators in them.
1. If limited regular expression globbing is used, at what point does using regular expression processing become more expensive or complicated than using simple string manipulation functions?
1. Should the regular expressions or interesting strings be moved to the application configuration file?
1. Instead of renaming the `categories` column to `course_id`, process `categories`, assign it to `course_id`, and then drop `categories`.

**Comment by zqian** [comment]
I have spot-checked a couple MiVideo files in a couple of course, in_context vs inside Media Gallery tool. Looks good.
