### ISSUE TITLE
Remove user table to minimize PII collection

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#152]
After discussion and back-and-forth with various stakeholders, we've determined that the `user` table is not necessary for current reporting purposes, and that it should be removed to minimize Personally Identifiable Information (PII) collection. For now, the `user_id` in the `enrollment` table should be maintained to assist with generating student enrollment counts. Changing this will require a migration dropping the table and several modifications to `AsyncEnrollGatherer`.

**Comment by zqian** [comment]
verified user table is no longer in database, and cron job works fine after the change.
