### ISSUE TITLE
Some config schema and defaults adjustments to be less restrictive

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#154]
I started to run this a bit more locally and there's a few small changes we should make to the schema

- minLength should be removed from
  - CANVAS_TERM_IDS since ADD_COURSE_IDS can be used. This is useful for testing to use specific courses rather than pull down entire terms.
  - MIVIDEO -> kaltura_user_secret and kaltura_categories_full_name_in as Kaltura report may not be run (Alternatively some default in the env_blank can be provided for kaltura_user_secret so it passes this check. There is already a value for the other)

- INVENTORY_DB in the env_blank should be configured to match the local database by default
```
    "INVENTORY_DB": {
        "host": "course_inventory_mysql",
        "port": "3306",
        "dbname": "course_inventory_local",
        "user": "ci_user",
        "password": "ci_pw"
```

**Comment by jonespm** [comment]
Umm, I accidentally pushed this one right to master. 

Going to have to turn on protection for that.

**Comment by ssciolla** [comment]
Bummer. I don't think it has to be reverted, but I probably would have requested some things like a comment noting these are the creds for the local database in Docker. I also don't really like stand-in strings (I think I asked @lsloan to make this empty), but I can understand how it's frustrating when the minimum length is longer. I guess I figured people who weren't using `MIVIDEO` would just comment out or remove this object (it's not required), but maybe that wasn't a realistic assumption. Anyways, TLDR, let's just go with it.

**Comment by ssciolla** [comment]
For what it's worth, the `minLength` removal was a good call, and I kinda feel like I didn't originally mean to include that (because of `ADD_COURSE_IDS`).
