### ISSUE TITLE
Optimize the Published date process 

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/course-inventory#156]
Canvas is having problems with Audit Log API and due to that fetching the published date is taking time. Here is the proposed solution

1. Try to get the courses published date only for the courses that don’t have then and not just the whole set
2. Add a retry Mechanism if error encountered for attempts that is configurable
3. add a Timeout

**Comment by ssciolla** [comment]
This is related to issue #21.

**Comment by zqian** [comment]
Verified working in test Jenkins. Process only took about 15 minutes, instead of 1 hour and 24 minutes without the change.
