### ISSUE TITLE
Fix custom logging format

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#157]
Before `run_jobs.py` was implemented, we had a custom logging format configured for the `inventory.py` job. It looks like the migration of that to `run_jobs.py` with the simultaneous creation of `environ.py` led to this being lost.

This should be fixed if we move the `basicConfig` call in `run_jobs.py` to `environ.py`.

https://github.com/tl-its-umich-edu/course-inventory/blob/4853fe5e74d7d98b8d88e2835fb1ee5fe525e4ea/run_jobs.py#L19-L22

**Comment by lsloan** [comment]
I like the formatting the way it is currently, but I'd like to see the addition of the function name.  Looks like adding `funcName` to the format string could do that.  See: https://docs.python.org/3/library/logging.html#logrecord-attributes

**Comment by zqian** [comment]
verified the log message format change on the test cron output.
