### ISSUE TITLE
Refine error case of make_request_using_api_utils

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#161]
_Raised by @pushyamig during review of PR #151_

Currently, the `make_request_using_api_utils` function always returns a `Response` object, even if the request failed three times. Though this hasn't ever happened in my memory, we should revisit the return type of this function and whether or not we want the program to continue after failing in this way.

**Comment by zqian** [comment]
Please see the latest handling in issue #184
