### ISSUE TITLE
All SIS ID data types should be VARCHAR(256)

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#165]
In some local testing, @pushyamig found that sometimes the `account.sis_id` can sometimes contain trailing dashes and hyphens. While these are infrequent, the data type should either be flexible enough to handle this, or there should be an additional function that validates this field and sets invalid values to `None`.

Edit: After further discussion, we decided that to keep things simple, all SIS IDs (for `course`, `course_section`, and `account`) should use the same data type of `VARCHAR(256)`, as the Canvas data model specifies them as `varchar`. This leniency will prevent errors and leave custom validation logic out of the code, while still allowing joins on valid IDs to the SIS dataset.

**Comment by zqian** [comment]
Verified the sis_id in account, course and course_section table are of VARCHAR type. It is still of int type in term table. I will update the issue title to reflect this.
