### ISSUE TITLE
Migration 0017 is repeated

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#166]
It looks like I may have neglected to bump the migration number for the migration that was part of PR #138. While I don't think will break anything, I think it will be clearer if we keep these numbers unique.

**Comment by jonespm** [comment]
Yeah I was thinking about this too and it kind of goes back to the idea of wanting migrations for different projects to be able to be separated. Having migrations in one space with multiple people working on it will frequently cause this to happen.

I think we'll either need to break up the migrations into separate directories or at maybe prefix the files and keep them independent. Though that would break what we have now. I've had to bump the name of the file in the PR I'm working on 3 times already and it all just depends what gets merged first.

Maybe leave the past as-is and think about a better solution for the future migrations?

**Comment by jonespm** [comment]
Also if anyone had run this migration with the prior name it will mess up for them and they'll have to either dump their migration or manually roll it back, right? :/

**Comment by ssciolla** [comment]
Yes, they may have to wipe out their database, but that's fairly easy to do on a local development machine. I agree there are certainly issues with the current migration setup. Also, we (including myself) have been pretty inconsistent with our use of `__depends__`. The number matters if there is no `__depends__`.

Anyways, this is going to bug me if they are the same. I'm sorry you've had to change yours multiple times. You can always go higher, like `0030`, until things are settled and you are ready to merge.

**Comment by jonespm** [comment]
Yeah, I'll just go to 20 for now. It doesn't depend on anything any other tables right now.

**Comment by zqian** [comment]
migration files are in good sequence now.
