### ISSUE TITLE
Create a Mixin or function to incorporate to_csv/to_sql and logging

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#172]
We could *probably* clean up this logger/to_csv/to_sql code and make this a function somewhere. Or a method in a Mixin that both of these classes extend. This also might make it easier when the upsert comes.

I guess I'll just hardcode it here for now.

_Originally posted by @jonespm in https://github.com/tl-its-umich-edu/course-inventory/pull/155/review_comment/create_

**Comment by ssciolla** [comment]
This issue is related to (or a duplicate of) #149.

**Comment by jonespm** [comment]
Closing as Won't Fix, I think our logging is sufficient for now.
