### ISSUE TITLE
Update .dockerignore to ensure HJSON files are excluded, use proper syntax

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#180]
As part of PR #134, I neglected to update the `.dockerignore` file, which tells Docker which files to disregard when building images. While this isn't a huge risk, it is possible for developers who are using a mixed approach of `virtualenv` and `Docker` to include credential files in images that they build locally if they are keeping a copy of their `env.hjson` in `config/secrets`. To eliminate that risk, we should update the patterns in `.dockerignore` to cover the new HJSON file ending.

https://docs.docker.com/engine/reference/builder/#dockerignore-file

**Comment by ssciolla** [comment]
While looking into this, I also discovered that the `.dockerignore` syntax works a little differently than `.gitignore` syntax. Previously I had expected them to be the same. To find files with certain patterns recursively in all child directories, you need to use the special Docker `**/` syntax.

**Comment by zqian** [comment]
To test:

- comment out the :/app line under services->job -> volumns within docker-compose.yaml
- docker-compose build; docker-compose up -d; docker exec course_inventory /bin/bash
- verify those files are not in the docker image, e.g. no env.hjson inside config folder, etc.
