### ISSUE TITLE
Use custom exception rather than exiting so other jobs can continue

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#184]
Possible the better thing to do if we just wanted to abort this job would be to raise a custom exception, catch it up in run_jobs. Then the other jobs could continue when this one fails. 

Jenkins would still consider this script a failure but it wouldn't block anything else. I'm fine if you want to consider this for the future. I'm going to unresolve this as we may want to create a new issue for this.

_Originally posted by @jonespm in https://github.com/tl-its-umich-edu/course-inventory/pull/177_

**Comment by zqian** [comment]
Test steps as @ssciolla suggested, tested this locally by editing "any of the Canvas request functions (I usually add an a to the end of the request URL ending for the term process). That will fail with repeated 404 errors and you’ll see the exception triggered:
Like change line 87 of inventory.py to the following: 
term_url_ending = url_ending_with_scope + str(term_id) + 'a'
"

The test is a success:

- The failed job did not stop others from running. 
- I got the expected messages in the log file:
"2020-06-05 09:53:53,515 - __main__ - run - ERROR - JobError: Data could not be gathered from the URL with the ending "aa/CanvasReadOnly/accounts/1/terms/167a"
2020-06-05 09:53:53,515 - __main__ - run - ERROR - An error prevented the COURSE_INVENTORY job from finishing
2020-06-05 09:53:53,515 - __main__ - run - INFO - The program will continue running other jobs"
- no data inserted into job_run table.
