### ISSUE TITLE
some MiVideo course IDs improperly converted

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/course-inventory#188]
## Summary

Some Kaltura media category values have long alphanumeric ID strings in them, which are being improperly interpreted as much smaller integers.

## Details

While looking into other issues, it was noticed that several course IDs in the `mivideo_media_courses` table refer to Canvas courses that do not exist.  For example, course 7 seems to have a lot of activity based on the data, but couldn't be found in Canvas.  Tracing backwards by looking for Kaltura media IDs used in courses with IDs less than 100, then looking up the media in the KMC (Kaltura Media Console for admins), I found that the categories for the media included values like:

* 7 → `Canvas_UMich>site>channels>7db438071375c02373713c12c73869ff2f470b68>InContext`
* 2 → `Canvas_UMich>site>channels>2f8b82d7f60deb59f1d5e288938371afc21c53d4>InContext`
* 92 → `Canvas_UMich>site>channels>92f035182d38b4bf499ad346fef5c2c77617b371>InContext`

Note the alphanumeric Canvas course IDs.  When these are processed by regular expression, the first nonnumeric character and everything after it is truncated.

Some of the same media had more than one category, and some of those had numeric IDs in them that are correct references to Canvas courses.

## Solution

Fix the regular expression that interprets Kaltura category strings as Canvas course IDs to consider only those that are numeric only, not alphanumeric.

Specifically, the IDs should be numeric only, either at the end of the category string or immediately followed by `>InContext`.

## Related

It may make sense to fix this problem together with these issues:

* #150  
* #183

Given the shortness of time for 2020.02.01 to be released, it's best to keep this issue separate from the others.

**Comment by zqian** [comment]
After the fix, the lowest number of the course id should be 99, no more single digit ids.
