### ISSUE TITLE
Change Python 3.7 image to Python 3.7-slim (or 3.8)

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#191]
I believe that this script only really needs the Python 3.7 slim image.

This should save about 10GB in size on each image.

This is something I'm looking to try to do for all images.

Also can we use 3.8 as 3.7 will be out of support soon.

**Comment by jonespm** [comment]
**3.8-slim** = Downloads more packages to download in step 2 and takes about 4 minutes to complete the build locally without any image layers. LTI runs without any issues with Python 3.8. Job size is 742MB

**3.7** = Less packages to download in Step 2. Takes about 3 minutes to complete and build locally without any image layers. Job size is 1.21GB. 

So sounds like using slim reduces the size by about 40% but it takes about a minute longer to build for Step 2 (Which shouldn't happen often)

**Comment by jonespm** [comment]
Python 3.8 also seems like it works fine for the LTI job. I'm going to include that. I don't expect any regressions.

**Comment by jonespm** [comment]
Stage 2 of **slim** downloads 90 packages = 330MB. 
Stage 2 of **regular** downloads 6 packages = 1MB (since many are included in the base)

This takes about a minute in slim. 

The biggest packages are git and ldap. I don't feel like we need these to run.

**Comment by ssciolla** [comment]
I noticed that the `README.md` mentions Python 3.7; we should either update the mention to 3.8 or just say Python 3.

**Comment by zqian** [comment]
Matt has updated the README file. Local test was successful with the 3.8 image
