### ISSUE TITLE
Create a lookup table for LTI placement types

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#193]
It was requested on the DW meeting that we should have a lookup table for LTI tools something like

**lti_type**
```
canvas_id        (int)     # Actual ID from Canvas
des              (varchar) # Description/Name of the tool
rpt_group_nm     (varchar) # Group we define
```

This will map back to the placement id in `lti_placement`.

We'll generate a migration to populate this table. This will replace the environment variable `SUPPORTED_LTI_TOOLS`

**Comment by jonespm** [comment]
Ok, I updated it.

In the provided model from Jeff he has. Maybe I can just use the same without the `lti_` prefix

```
lti_tool_cd: 12313 
lti_tool_des: Bluejeans
lti_tool_rpt_group_nm: Zoom
```

**Comment by lsloan** [comment]
# QA – ✅ 

* DB: `lms_canvas_test` on `stage-ld-mysql-db.miserver.it.umich.edu`
* `_yoyo_log` table
  * Migration logged:
     |id                                  |migration_hash                                                  |migration_id          |operation|username       |hostname                   |comment|created_at_utc       |
     |------------------------------------|----------------------------------------------------------------|----------------------|---------|---------------|---------------------------|-------|---------------------|
     |7984d4ea-b177-11ea-ab7a-0a580a810687|7bb55b7ad9c311486f30685a27cf8eb3e4c20d274bdcaa3cc46fafdbdd62b775|0022.add_lti_type                  |apply    |tl-jenkins-test|course-inventory-test-stage|       |2020-06-18 15:22:09.0|
* `lti_type` table
  * contains the following 
     |canvas_id|des      |rpt_group_nm|
     |---------|---------|------------|
     |     4352|Bluejeans|Bluejeans   |
     |    25194|Zoom     |Zoom        |
  * Incidentally, `Bluejeans` should be capitalized as `BlueJeans`. ¯\\\_(ツ)_/¯

* application configuration
  * `env_test.hjson` in OpenShift `tl-jenkins-test` project modified to remove the `$.CANVAS.SUPPORTED_LTI_TOOLS` object.
  * The application runs successfully without this object.
  * The application had been run with this config. change **_before_** this issue's PR was merged and the application failed at that time.  The fact that this config change now works in combination with the code change is a good sign.
