### ISSUE TITLE
course.name data is not unique

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#198]
The Canvas data model does not enforce uniqueness on the name property (https://portal.inshosteddata.com/docs#course_dim), but we are doing it in our database. This resulted in a production error when two courses with the same name, but different IDs, were encountered. The uniqueness constraint needs to be removed.

**Comment by lsloan** [comment]
# QA – ✅ 

* DB: `lms_canvas_test` on `stage-ld-mysql-db.miserver.it.umich.edu`
* `course` table
  * No longer includes `name` as a unique index
  * Found two courses named "Introduction to the R Statistical Computing Environment": 371074 and 371753
* `_yoyo_log` table
  * Migration logged:
     |id                                  |migration_hash                                                  |migration_id          |operation|username       |hostname                   |comment|created_at_utc       |
     |------------------------------------|----------------------------------------------------------------|----------------------|---------|---------------|---------------------------|-------|---------------------|
     |79df7de6-b177-11ea-ab7a-0a580a810687|b43ddbd2e7203202d4762678318556f659b71ec0df9aea0c32dbc3ae6116e13b|0023.relax_course_name|apply    |tl-jenkins-test|course-inventory-test-stage|       |2020-06-18 15:22:09.|
