### ISSUE TITLE
Retry mechanism when fetching course Published date

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/course-inventory#21]
For getting the published date, with sequential fetching of data takes a long time so we opted for the Asynchronous call approach, but sometimes we have seen canvas throws error for certain courses or we might encounter some internal code errors as well
`500  {"errors":[{"message":"An error occurred.","error_code":"internal_server_error"}],"error_report_id":7024627224}`

We could fix this by some sort of retry mechanism and with async calls.

**Comment by pushyamig** [comment]
@zqian @jennlove-um The work that I put in for the fetching published date seems to be temporary and canvas seems to be releasing a new API with all the course info probably next week `“/api/v1/audit/account/courses/:account_id” `. 
I don't know if we want to implement this issue. The approach we take using that API will be totally different then. Thoughts??

**Comment by ssciolla** [comment]
@pushyamig, we can close this, right?

**Comment by pushyamig** [comment]
YEs
