### ISSUE TITLE
Reveal sections info for Canvas courses

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/course-inventory#23]
Canvas courses can contain multiple sections. We need to create a separate table to capture this one-to-many relationship. The course_section table should include the following attributes:

1. Canvas course id
2. Section id
3. Section name
4. Section SIS ID
5. Section type: lecture, lab, discussion, etc.

**Comment by ssciolla** [comment]
@zqian, is there a good API endpoint to use for this? I didn't find any way yet to fetch sections in bulk, so I'm concerned that it's going to be similar to the `published_date` thing, where we need to make tens of thousands of requests. I will look into whether GraphQL can surface any of this.

**Comment by zqian** [comment]
@ssciolla try this UDW query:

select * from course_section_dim csd  where course_id like '%<canvas_course_id>'

**Comment by ssciolla** [comment]
Okay, but that's a different approach. I could make this work with UDW fairly quickly, but if we want to move to API eventually...

**Comment by zqian** [comment]
True. Let me search for the API then

**Comment by zqian** [comment]
How about the sections API? https://canvas.instructure.com/doc/api/sections.html#method.sections.index

**Comment by zqian** [comment]
GraphQL?

https://community.canvaslms.com/thread/37311-with-the-canvas-api-how-can-you-get-a-list-of-all-sections-for-a-term

**Comment by ssciolla** [comment]
I will look into GraphQL, though if we do that, we may want to change a bunch of stuff at once.

**Comment by ssciolla** [comment]
Closing this now. Related work continues on this in issue #42.
