### ISSUE TITLE
Update README with OpenShift and migration details

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#26]
Recent work on this project revealed a couple new or missing details from from the `README`. Specifically, we need to define `USER` as an environment variable in OpenShift for `yoyo-migrations` to work properly. Also, we should add at least a sentence about specifying migration dependencies with `yoyo`.

**Comment by jonespm** [comment]
Resolved by #27

**Comment by zqian** [comment]
Verified README contains details of yoyo-migrations.
