### ISSUE TITLE
Switch configuration from JSON to something else

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#29]
I used YAML previously to configure the online meetings, we should switch the config for this over to using that. The biggest advantage would be being able to add comments to the config. In addition pasting in API keys and strings that span multiple lines is easier with YAML since they don't need to be quoted.

This can convert over the sample really quickly, then we just need to populate the production and make a few minor code changes to read the YAML instead of the JSON. 

https://www.json2yaml.com/

In addition to this, move the comments from the README.md related to these variables into the YAML file. 

In this article ["Why JSON isn't a good configuration language"](https://www.lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language/) they mention altenratives like TOML, HOCON, HJSON. I like the idea of using something like HJSON or YAML because it would still be compatible with the files people are currently using.

They also link to an article [YAML: probably not so great after all](https://www.arp242.net/yaml-config.html) which is worth a consideration.

**Comment by pushyamig** [comment]
From the master branch, I was able to test all the process ["COURSE_INVENTORY", "MIVIDEO", "CANVAS_ZOOM_MEETINGS"], with .hjson file. I will make it pass
