### ISSUE TITLE
Get Canvas course & meetings code to use the database

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#31]
Rather than writing files to the filesystem, we should be using the database in this project.
This will require
- [ ] Generate required migrations
- [ ] Adding to the migrations
- [ ] Deleting and adding the values instead of to_csv (with pandas to_sql for now)
- [ ] The index for ZOOM_CONFIG should probably be made into an int and we should have a mapping table indicating what this came from.

**Comment by pushyamig** [comment]
I am assigning this issue to myself. I will take this up once I have a PR open for #25

**Comment by zqian** [comment]
I removed the BlueJeans label from this ticket, since BJ is responsible for the BJ report now.

@jonespm please validate whether this issue is still valid given the Zoom report status.

**Comment by jonespm** [comment]
Yeah, the scope of this has changed to just be for the Canvas course & meeting tables. We can update the title.
