### ISSUE TITLE
Write a central manager script for this project

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#33]
This project is becoming a combination of a number of reporting scripts. We should (for now) have a central manager that will start the appropriate report.

- [x] Refector the reports into packages/classes so they can be launched by a central script
- [x] Create a script at the top level like run_reports.py. This should take a command line option for which report(s) to run. 
- [x] This central script should take care of things like report timing, config loading, exception handling and anything else that might be common to each job.
- [x] After loading env file use values from the environment if they are present
I think it would just be something like this `ENV.update((key, os.environ[key]) for key in ENV.keys())`

**Comment by ssciolla** [comment]
@jonespm, I started working on this. I can go down the command-line argument path, but I was wondering whether we might ever want to run multiple jobs. What if we defined the names in the `env` file? Would that be bad for some reason?

**Comment by jonespm** [comment]
I was just expecting we might have multiple jobs in Jenkins like
Run Zoom Reports
Run Canvas Reports
Run Blue Jeans Reports

We could have each one use a different env file I guess, or pass different command line args. It seems like both could work the same way, so it doesn't matter how you want to implement it. I also have an idea for overriding the values in the ENV file with local environment values that I was going to do for this and MyLA so we could just do that too and keep it simpler. 

So the Jenkins job could like define local env of
REPORTS_TO_RUN=zoom,bluejeans
python run_reports.py

And the REPORTS_TO_RUN from os.environ would override the value(s) in the file.

**Comment by ssciolla** [comment]
Okay, how about something like this, @jonespm? 

https://github.com/tl-its-umich-edu/course-inventory/compare/master...ssciolla:issue-33-create-job-manager

**Comment by jonespm** [comment]
Yes, that is looking pretty good Sam. I just read through it but it's pretty much what I was thinking. Here's some things we'll have to think about.

I think each "module" should be responsible for its own migrations and this central job should run them all (kind of like how Django works). The Zoom tables aren't dependent on the Canvas tables for example. So we might need some changes to the DBCreator. (Haven't looked into that)

Seems like a good start though!
