### ISSUE TITLE
Append table changes for Zoom script

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#34]
After #14 and #31 is done, we'll want to just do incremental updates for the Zoom script so it will only collect data since the last run. Since Zoom only uses a date as a parameter from the last run (instead of a datetime) we might have to do some work here.

Pandas to_sql is going to fail if it encounters a duplicate row we either have to
- Insert each row one at a time and try/except the error if it fails
- Select all of the primary keys from the database (maybe date limited) and remove the duplicates from the dataframe before inserting. 

As far as zoom, this will also allow us to use an empty "to" date and just remove the duplicates in there.

**Comment by jonespm** [comment]
We also want to look at why client_timezone is hardcoded and if changing that makes a difference.

**Comment by zqian** [comment]
@jonespm I have removed the mention of BlueJeans and also dropped the label for BlueJeans.

**Comment by jonespm** [comment]
I'm just going to close this then, I don't think the Zoom part is something we'll work on either.
