### ISSUE TITLE
Methods should all be timed to check execution

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#36]
Should use a decorator and mark everything we want to time like: https://medium.com/pythonhive/python-decorator-to-measure-the-execution-time-of-methods-fa04cb6bb36d

_Originally posted by @pushyamig in https://github.com/tl-its-umich-edu/course-inventory/pull/30_

**Comment by ssciolla** [comment]
I kind of like the decorator option using `wraps` decorator described in the first answer to this question on StackExchange: https://codereview.stackexchange.com/questions/169870/decorator-to-measure-execution-time-of-a-function

**Comment by jonespm** [comment]
The decorator should just call and return the method it decorates. If it needs to return timing information (rather than just logging it) I'm not sure the best way to do that. I think we just wanted to print info messages before and after.

**Comment by jonespm** [comment]
We have some basic timing now, but there's a comment on how this could be improved. Marking this as enhancement.

https://github.com/tl-its-umich-edu/course-inventory/blob/2e27243e018180e38d049747500d6c93129ad91c/run_jobs.py#L70

**Comment by jonespm** [comment]
Closing as I don't think we really need this feature
