### ISSUE TITLE
Zoom/Canvas/JS script needs to masquerade as user to work correctly

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#39]
It looks like at least for Zoom the email/token that's being used might not be one that's registered to work on Zoom. We need to [masquerade](https://canvas.instructure.com/doc/api/file.masquerading.html) as a different user that does have access.

**Comment by zqian** [comment]
@jonespm is this ticket still valid now, after the Zoom/BlueJeans reports have been delegated to other teams?

**Comment by jonespm** [comment]
Yes, this is related to the Canvas script that figures out which meetings are in which course.

**Comment by jonespm** [comment]
It looks like this is not going to be needed as we're going down a sponsorship account route. I'm going to close this and re-open it only if it's needed.
