### ISSUE TITLE
Move .flake8 and .vscode from online_meetings to top level

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#44]
I think the settings in .vscode are good and enable linting by default. Also we should have a flake8 top level that's configured for this project. Some of the rules I'm okay with excluding and I've defined a few already. 

@pushyamig @ssciolla Okay with you? I noticed .vscode was in the .gitignore so didn't want to change this before then. 

This will also involve resolving all flake8 issues present in the other scripts. 

- [x] Move .vscode and .flake8
- [x] Remove .vscode from .gitignore
- [x] Verify that the rules we want excluded in .flake8 are accurate
- [x] Fix the code to adhere to flake8 rules (VSCode should light up with all the problems)
- [ ] Update Codacy to ignore the same rules (Though I think it will use the .flake8 config we have)

**Comment by ssciolla** [comment]
That's fine with me. I've been in the habit of .gitignore-ing IDE files for some reason, but I think if we want to adopt particular style guidelines, removing it from `.gitignore` makes sense.

**Comment by jonespm** [comment]
FYI I'd also love to do this same thing for MyLA ;)

**Comment by jonespm** [comment]
These were the rules I added to ignore
E501 - I feel like 79 is too short for a line length and I don't see any way to configure it to be longer. If there was I'd be happy with a longer line length. 
E401 - I personally think multiple imports are more readable that a ton of lines of separate imports
E111, E114 - The multiple of 4 indentations doesn't always seem to be the best, sometimes 2 feels better, and I think it was causing firing this on a tab. We could enforce this though.

```
    E501,  # line too long
    E401,  # multiple imports
    E111,  # Indentation is not a multiple of 4
    E114,  # Indentation is not a multiple of 4 comment
```

**Comment by jonespm** [comment]
Looks like this might work
```
[flake8]
max-line-length = 100
```

**Comment by ssciolla** [comment]
> E111, E114 - The multiple of 4 indentations doesn't always seem to be the best, sometimes 2 feels better, and I think it was causing firing this on a tab. We could enforce this though.

I kind of like indentation being consistent, and four seems to be what's expected in Python. The only place I'd be unsure is if there was JavaScript-like syntax (GraphQL comes to mind). Where else would you want 2 instead of 4 in Python files?

**Comment by jonespm** [comment]
No, I don't think there's any reason. flake8 is just for python so wouldn't check for any javascript, that would have to be in a different linter.

**Comment by jonespm** [comment]
I'll work on this when the two current PR's get merged, working on database stuff right now.
