### ISSUE TITLE
Reporting on other LTI tool usage

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#49]
Currently canvas_zoom_meetings does reporting on Zoom LTI placements. This should be more generalized to report on and LTI placement. Some tools may need custom code to get deeper integration. 

I believe this will also change the database model as we have a common table with all LTI tools. 

Other tools included involve ProctorU and BlueJeans (currently) but there may be more.

Requested by @zqian

**Comment by jonespm** [comment]
@zqian Did you do this for ProctorU? I can change this class around on Monday just didn't want to duplicate. I'm guessing maybe we could just pass in the tools we want to look for. It would probably be "best" to do external id's but maybe doing the names is okay too.

**Comment by jonespm** [comment]
After #155 is merged, I'm going to work on this one and probably change this all around here to be more generic.

- [ ] Rename online_meetings -> lti_placements
- [ ] Refactor out the non-zoom code from canvas_zoom_meetings into a new file lti_placements. This includes zoom_course_report, everything in the main, and some of the code in get_zoom_course around creating the lti_placement table. 
- [ ] Add support for "generic" LTI placements that don't need special processing.

**Comment by zqian** [comment]
Verified the LTI_placement table now contains data for both BlueJeans and Zoom LTI tools
