### ISSUE TITLE
Issue with UUID duplicate dropping?

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#52]
Might be off-base here, but doesn't the resulting dataframe need to be re-assigned here? 

[report, lines 93-95](https://github.com/jonespm/course-inventory/blob/373ea575e5ea6830f68a022a02cd0d684a758002/online_meetings/report.py#L93-L95)

My understanding is that it doesn't mutate. See [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html).

**Comment by ssciolla** [comment]
Oh, doh, just saw the `inplace`; I've never used that. I'm closing this.

**Comment by jonespm** [comment]
It actually isn't a bad suggestion and we can switch it. It's not a bug though as you've noticed. I think this is related to #40 and can be switched then. 

I've used inplace often in the past but aside from fillna it doesn't seem like it has much of an advantage and internally it just creates a new object anyway. And they're talking about making it a FutureWarning. Some of the confusion here seems like developers don't really know if there's an advantage to using it or not. 

https://github.com/pandas-dev/pandas/issues/16529
