### ISSUE TITLE
Refactor zoom classes to supply a term or course

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#53]
When running the "canvas_zoom_meetings" it should either allow to supply an entire term to report on or a list of individual courses. This should also remove the test code that is present around like 55 for testing an individual course.

_Originally posted by @ssciolla in https://github.com/tl-its-umich-edu/course-inventory/pull/50_

**Comment by ssciolla** [comment]
I used this in my testing, it's working for me. QAed!
