### ISSUE TITLE
Clean up payloads in blue jeans report to pass as params and dicts

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#56]
You should be able to just define this as a dictionary rather than a string, would save on some quote escaping. If it's an API that needs json encoding the you should still define it as a dict and when posting it call `data=json.dumps(payload)`. Requests also lets you call `json=payload`.

_Originally posted by @jonespm in https://github.com/tl-its-umich-edu/course-inventory/pull/48_

**Comment by zqian** [comment]
BlueJeans team is now responsible for the BJ reports.
