### ISSUE TITLE
integrate MiVideo usage data

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/course-inventory#65]
Integrate the data showing the usage of MiVideo media in Canvas.  That is, the data that shows how many `MediaEvent`→`Started` Caliper events are found in UDP per course ID per hour.

The MiVideo media creation data will be covered in #92.

**Comment by pushyamig** [comment]
I ran the Mi video job. I had my personal BQ service account file and I saw a mivideo Table populated in the Local DB. 

Test passing
