### ISSUE TITLE
Use a smarter method with docker-compose to determine when the MySQL database is ready and remove hehe from log message

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#67]
Right now `run_jobs.py` just waits 30 seconds for the MySQL container to finish initializing, but really it only needs to do that on the first startup. Otherwise, it takes three seconds. MyLA has a better strategy for this. See Matt's comment below.

"I'm doing this in the MyLA start script with the nc command which should be installed by default. 
```
echo "Waiting for DB"
while ! nc -z ${MYSQL_HOST} ${MYSQL_PORT}; do   
  sleep 1 # wait 1 second before check again
done
```

I believe the we could have a shell script before this python or could just do this similar check in python with nc. (I didn't test this code below)

```
while not os.system(f"nc -z {os.getenv("MYSQL_HOST")} {os.getenv("MYSQL_PORT")}):
    time.sleep (1)
```"

_Originally posted by @jonespm in https://github.com/tl-its-umich-edu/course-inventory/pull/62_

**Comment by lsloan** [comment]
This is pretty excellent.  I made a `FIXME` comment in my own copy of the code that this needs to be done.  I'm glad others are thinking the same way.

90% of the time I run the app with docker-compose, the DB service is running and ready for use, but the program waits the 30 seconds anyway.

**Comment by ssciolla** [comment]
This was a problem I had identified before submitting the `run_jobs.py` PR, but @jonespm said we could resolve if it after we merged. Thus, PR #81.
