### ISSUE TITLE
Improve README formatting, check for markdownlint rules

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#68]
Codacy has tagged some README issues related to tables, but also @lsloan offered the below suggestion in his review of PR #62.

"A general suggestion for Markdown docs:  Break long lines at 80 characters.

MD docs are meant to be readable in raw form as well as having a well-defined transformation to a pretty form.  Not all document viewers will wrap long lines (or wrap them well).  It's helpful to assume the document will be viewed in its raw form in a poor environment.

It also localizes changes.  Like if the above very long line were changed just to add a word, it would be easier to see the change if it were in one of several shorter lines."

_Originally posted by @lsloan in https://github.com/tl-its-umich-edu/course-inventory/pull/62#discussion_r404914116

**Comment by jonespm** [comment]
I started fixing some of these issue related to the linting. I'm not worried about the issues with the tables since those are optional but there are a few others. I'm adding in a .markdownlint.json file with a configured line length of 120 which I'm matching up with the Python code. Most consensus out there now is a 120 line length is fine. I use a vertical monitor and I can fit 125 characters comfortably in my IDE on a line.

**Comment by jonespm** [comment]
120 isn't becoming very realistic. I'm breaking on periods and rewriting some long lines but we still have about 20 lines over that that aren't super easy to rewrite without breaking at irregular spots. What do you think, have a longer line limit or continue to rewrite run-on sentences?

**Comment by ssciolla** [comment]
Why can't we just break at 120 characters or the nearest complete word? I haven't seen what you're changing, but I think re-writing text to satisfy README style is not a good idea.

**Comment by jonespm** [comment]
I feel like breaking on a word just to achieve a line length isn't great for being able to edit this in the future. I also started breaking on commas which seems okay. 

I did some very minor edits, to break the lines you can of course review.

**Comment by ssciolla** [comment]
Okay, sure, I will take a look whenever it's ready. Some of the issues you are describing are why I left wrapping up to VSCode/GitHub/etc.
