### ISSUE TITLE
move migration code out of `course_inventory` module

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/course-inventory#71]
If the application is not run with the `"COURSE_INVENTORY"` module reference in the `"JOB_NAMES"` array of `env.json`, then the DB migration code is never run.  That means tables are never set up or updated for any of the other modules.

Possible solutions:

* Move the migration code up to `run_jobs.py`.  (Probably the simplest solution.)
* Each modules should call the migration code.  This may mean that each module needs to either:
  * Specify which application-level migrations are required by it.
  * Each module contains its own set of migrations.  (Probably the right solution.)

**Comment by ssciolla** [comment]
@lsloan, I might be missing something, but I think first possible solution is already the case. `run_jobs.py` is running `db_creator_obj.migrate()`, and `inventory.py` is only running `db_creator_obj.drop_records()`.

https://github.com/tl-its-umich-edu/course-inventory/blob/079d22d4251e285236653bc065f46a03381c6a30/run_jobs.py#L128-L130

https://github.com/tl-its-umich-edu/course-inventory/blob/079d22d4251e285236653bc065f46a03381c6a30/course_inventory/inventory.py#L262-L266

**Comment by ssciolla** [comment]
I feel that creating separate migrations for each module would over-complicate this project. The end goal is get all of the data into one database, so managing migrations at the highest project level seems to make sense to me.

**Comment by ssciolla** [comment]
We may need to modify `drop_records` so that it can be used in individual jobs without affecting tables populated by other jobs.

**Comment by lsloan** [comment]
This may be an issue of the migrations having already been run previously and I wasn't aware of it. I'll check into that and if that's the case, then I'll close this issue.

**Comment by lsloan** [comment]
That was the case!  Closing…
