### ISSUE TITLE
Consider re-factoring drop_records in db_creator

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#72]
Right now, `DBCreator.drop_records` drops records from all tables not specified in `APPEND_TABLE_NAMES` (also excluding `yoyo`-related tables) and it is only being used in `course_inventory/inventory.py`. However, if other jobs want to use `drop_records`, they will also have to drop tables related to 'inventory.py`, and `inventory.py` will drop their records, and back and forth.

Perhaps `drop_records` should take an optional argument specifying the tables to be dropped.

**Comment by ssciolla** [comment]
I've been thinking about this more and the `APPEND_TABLE_NAMES` idea. I'm kind of wondering now if specifying append tables was the wrong approach; shouldn't the default behavior be NOT to drop records? Instead, maybe we should change `drop_records` to accept a list of table names to drop, which are then validated using `DBCreator.get_table_names()` before records are actually deleted? Then anyone who wants to use this can manage their own tables, specifying tables as part of their job rather than in a configuration file. In my experience, `APPEND_TABLE_NAMES` has proven error-prone and confusing. I guess there was a lack of foresight on my part : (

**Comment by lsloan** [comment]
:shipit:
