### ISSUE TITLE
Flake8 identified response_data as not being used in inventory.py

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/course-inventory#75]
Was this method intending to return the response_data or just the response? This should be double checked and just do a json.loads if we're trying to get an exception. This seems like it could be a bug but assigning someone that knows more about this code.

https://github.com/tl-its-umich-edu/course-inventory/blob/079d22d4251e285236653bc065f46a03381c6a30/course_inventory/inventory.py#L57

**Comment by ssciolla** [comment]
Yeah, I can change this. I figured it was pretty harmless to assign to something, but it's not necessary.
