### ISSUE TITLE
make DBCreator class implement fluent interface

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/course-inventory#84]
For convenience, make the `DBCreator` class implement a [fluent interface](https://en.wikipedia.org/wiki/Fluent_interface).  In its most basic form, this means all the class' methods that currently return `None` would instead return the instance of `DBCreator` (i.e., `self`).

Such an interface would allow code like this:

```python
    db_creator_obj = DBCreator(INVENTORY_DB, APPEND_TABLE_NAMES)
    db_creator_obj.set_up()
    db_creator_obj.drop_records()
    db_creator_obj.tear_down()
```

To be written as this instead:

```python
    db_creator_obj = (DBCreator(INVENTORY_DB, APPEND_TABLE_NAMES)
        .set_up().drop_records().tear_down())
```

**Comment by ssciolla** [comment]
Makes sense. I'll try to handle this with some other changes I've been looking at to this class.
