### ISSUE TITLE
produce MiVideo media creation data

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/course-inventory#92]
This issue was split from #65.

Produce data about the creation times of MiVideo media and include relationships with Canvas courses, where applicable.

This may be based on Caliper events from UDP, as the manual process had been, or it may use the Kaltura API.

**Comment by zqian** [comment]
Verified the mivideo_media_courses and mivideo_media_created tables are populated.

I added another request #183 to insert FK to those MiVideo tables. Based on the data records now, there are many courses in the "mivideo_media_courses" that are not reported in the "course" table:

select  count(*) 
from mivideo_media_courses mmc 
where course_id not in 
(select canvas_id from course c2 )

I will mark the current issue closed for now.
