### ISSUE TITLE
generate participantMinutes for Zoom meetings

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/course-inventory#95]
Zoom meeting records does not have participantMinutes, vs BlueJeans data feed has that entry.

We can estimate the number by doing the following:

(end_time-start_time)*participants

**Comment by jonespm** [comment]
I believe this value is on https://marketplace.zoom.us/docs/api-reference/zoom-api/reports/reportmeetingdetails but looking at details of every meeting would be very process intensive if we aren't caching. I don't see where this is on every API.

We have almost 170000 meetings so running this API against that at the rate limits they have would take practically forever.

**Comment by zqian** [comment]
We only need to report on a limited list. We know the Zoom training meetings used by ITS Teaching and Learning.
