### ISSUE TITLE
Enums from run_jobs.py should be in a separate module

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/course-inventory#96]
The `ValidJobName` and `ValidDataSourceName` enumerations should be pulled out of `run_jobs.py` (possibly to a `vocab.py` module) so they can be used by different jobs' entry modules, as well as `run_jobs.py`, without creating a circular dependency.

**Comment by zqian** [comment]
verified the all jobs are registered in the vocab.py file.
